// MAZO COMPLETO TEMA 2 — 50 preguntas (versión concreta)
// Cada pregunta es autocontenida: no depende de recordar un "título" de tema,
// y cada respuesta incluye el dato exacto (artículo, %, condición) en vez de
// una etiqueta genérica.

const cards = [
    // --- Bloque 1: Principios generales (A1-A9) ---
    { id: 1, front: "Según el artículo 1 del TRLGSS, ¿a quién reconoce EXACTAMENTE el derecho a la Seguridad Social (sin mencionar aún extranjeros)?", back: "A los españoles. El art. 1 dice literalmente 'españoles' — los extranjeros entran por el art. 7 (extensión del campo de aplicación), no por el art. 1." },
    { id: 2, front: "Enumera los 4 principios del sistema de Seguridad Social que recoge el artículo 2.", back: "Universalidad, unidad, solidaridad e igualdad." },
    { id: 3, front: "¿Qué prohíbe expresamente el artículo 3 respecto a los derechos de Seguridad Social?", back: "Prohíbe renunciar a los derechos que otorga la Seguridad Social — son irrenunciables." },
    { id: 4, front: "¿Qué 3 funciones ejerce el Estado sobre el sistema de Seguridad Social (arts. 2 y 4)?", back: "Ordenación (regular el sistema), jurisdicción (resolver conflictos) e inspección (vigilar el cumplimiento)." },
    { id: 5, front: "TRAMPA de examen sobre el A1: si en el enunciado te encuentras 'los españoles y extranjeros tienen derecho a la Seguridad Social según el A1', ¿qué está mal?", back: "El A1 literal solo dice 'españoles'. Añadir 'extranjeros' es un error inducido — esa extensión viene del art. 7, no del art. 1. Ojo también si cambian el número del artículo (1 al 9 son de la Constitución)." },
    { id: 6, front: "¿Cuáles son las DOS modalidades de la acción protectora según el artículo 7 (campo de aplicación)?", back: "Modalidad contributiva y modalidad no contributiva." },

    // --- Bloque 2: Campo de aplicación y composición (A7-A11) ---
    { id: 7, front: "Según el A7, ¿qué DOS requisitos exactos debe cumplir un sujeto para acceder a la MODALIDAD CONTRIBUTIVA?", back: "Residir en España Y trabajar (ejercer actividad en territorio nacional). Aplica a españoles y extranjeros que residan o se encuentren legalmente en España." },
    { id: 8, front: "Según el A7, ¿qué único requisito exige la MODALIDAD NO CONTRIBUTIVA?", back: "Solo residir legalmente en España — no hace falta trabajar (aplica a españoles y extranjeros que residan legalmente)." },
    { id: 9, front: "Cita los 5 colectivos incluidos en el sistema por 'trabajar en territorio nacional' según el A7.", back: "1) Trabajadores por cuenta ajena, 2) por cuenta propia/autónomos mayores de 18 años, 3) socios trabajadores de cooperativas de trabajo asociado, 4) estudiantes (seguro escolar), 5) funcionarios públicos civiles y militares." },
    { id: 10, front: "TRAMPA del A8: un abogado en ejercicio libre y que además es funcionario, ¿tiene que estar de alta obligatoriamente en los DOS regímenes a la vez (el de abogados y el de funcionarios)?", back: "NO. El A8 establece la prohibición de inclusión múltiple obligatoria: un mismo trabajo solo genera una única vinculación a efectos de encuadramiento. Solo se integraría en dos regímenes si una norma lo dijera expresamente." },
    { id: 11, front: "Nombra los 5 regímenes especiales que existen según el artículo 10 (además del Régimen General).", back: "RETA (autónomos), REMAR (trabajadores del mar), Funcionarios, Estudiantes, y Minería del Carbón." },
    { id: 12, front: "Según el A10, ¿cuáles son las 4 circunstancias que justifican crear un NUEVO régimen especial?", back: "1) Naturaleza de la actividad, 2) sus peculiaridades, 3) condiciones de tiempo y lugar, 4) índole de los procesos productivos." },
    { id: 13, front: "¿Cómo se llama el sistema especial dentro del RETA para los autónomos del sector agrario?", back: "SETA — Sistema Especial de Trabajadores por Cuenta Propia Agrarios." },

    // --- Bloque 3: Artículo 12 (familiares del autónomo) ---
    { id: 14, front: "Según el A12, ¿qué 4 requisitos deben cumplirse TODOS para que un familiar del autónomo tenga la consideración de CUENTA PROPIA (salvo prueba en contrario)?", back: "1) Vínculo (cónyuge o pariente hasta 2º grado por consanguinidad o afinidad, incluida adopción), 2) ocupación en el mismo centro de trabajo, 3) convivencia con el titular, 4) estar a su cargo." },
    { id: 15, front: "Un hijo MENOR de 30 años que trabaja para su padre autónomo Y convive con él: ¿en qué régimen puede optar quedar encuadrado y con qué exclusión concreta?", back: "Puede optar por Cuenta Ajena en el Régimen General, con exclusión de la cobertura por DESEMPLEO (sigue cotizando por el resto de contingencias, pero no genera ni paga la prestación de desempleo)." },
    { id: 16, front: "¿Cuál es el ÚNICO requisito adicional que el profesor remarca como imprescindible para que aplique la exclusión de desempleo del hijo menor de 30 (o mayor con discapacidad)?", back: "La CONVIVENCIA con el titular del negocio. Sin convivencia no se cumplen los 4 requisitos del A12, y el hijo se trata como cuenta ajena normal (SIN exclusión, cotizando también por desempleo)." },
    { id: 17, front: "Los trabajadores en Centros Especiales de Empleo (plantilla con ≥70% de trabajadores con discapacidad ≥33%) quedan incluidos como cuenta ajena, pero ¿en qué régimen EXACTAMENTE?", back: "En el régimen QUE CORRESPONDA según la actividad de la empresa — no siempre es el Régimen General; puede ser un régimen especial (p. ej. REMAR si el centro pertenece a una empresa marítimo-pesquera)." },
    { id: 18, front: "Los socios trabajadores de una COOPERATIVA DE TRABAJO ASOCIADO, ¿entre qué dos opciones de encuadramiento pueden elegir en sus estatutos?", back: "1) Asimilados a cuenta ajena, en el Régimen General o el régimen especial que corresponda según la actividad, o 2) Trabajadores autónomos (RETA)." },
    { id: 19, front: "¿Qué exclusión concreta se aplica SIEMPRE a los socios de cooperativas (de trabajo asociado o de otro tipo), independientemente de su encuadramiento?", back: "Quedan excluidos de FOGASA (Fondo de Garantía Salarial) en todo caso. No confundir esta exclusión con la de desempleo de los hijos de autónomos del A12." },
    { id: 20, front: "Un familiar con discapacidad exactamente del 65%: ¿en qué tramo entra — el que exige 'primera alta' o el que no la exige?", back: "En el tramo superior (≥65%), que NO exige que sea la primera alta en el sistema. El tramo intermedio (33% incluido a 65% NO incluido) sí exige que sea la primera alta." },
    { id: 21, front: "Da un ejemplo histórico REAL de actividad excluida del campo de aplicación por 'marginal y no constitutiva de medio fundamental de vida'.", back: "En 1972 se excluyeron las 'Sociedades de Fomento de la Cría Caballar de España' (art. 7, potestad del Gobierno)." },

    // --- Bloque 4: Encuadramiento y regla del semáforo (A136 / A305) ---
    { id: 22, front: "Define con tus palabras qué significa 'encuadramiento' en Seguridad Social.", back: "Es el proceso de determinar en qué régimen (general o especial) y en qué sistema especial (si aplica) queda incluido un trabajador según sus circunstancias." },
    { id: 23, front: "A136, Letra B: socio de SOCIEDAD DE CAPITAL SIN control efectivo y SIN funciones de dirección y gerencia. ¿Cómo queda encuadrado?", back: "Régimen General, como trabajador por cuenta ajena (sin ninguna asimilación ni exclusión especial)." },
    { id: 24, front: "A136, Letra C: socio de SOCIEDAD DE CAPITAL SIN control efectivo pero CON funciones de dirección y gerencia. ¿Cómo queda encuadrado?", back: "Régimen General, asimilado a trabajador por cuenta ajena (con las exclusiones de desempleo y Fogasa)." },
    { id: 25, front: "A136, Letra D: socio de SOCIEDAD LABORAL SIN control efectivo y SIN funciones de dirección y gerencia. ¿Cómo queda encuadrado?", back: "Régimen General, como trabajador por cuenta ajena." },
    { id: 26, front: "A136, Letra E: socio de SOCIEDAD LABORAL SIN control efectivo pero CON funciones de dirección y gerencia. ¿Cómo queda encuadrado?", back: "Régimen General, asimilado a cuenta ajena (con exclusión de desempleo y Fogasa, salvo que la sociedad laboral tenga más de 25 socios, caso en que la exclusión no es automática)." },
    { id: 27, front: "En la regla del semáforo, el caso 'ÁMBAR' (asimilado a cuenta ajena) exige TRES condiciones simultáneas. ¿Cuáles son?", back: "1) NO tener el control efectivo, 2) ejercer función retribuida de dirección y gerencia, y 3) ser consejero o administrador. Si falta cualquiera de las tres, el caso pasa a ser 'ROJO' (cuenta ajena pura, sin asimilación)." },
    { id: 28, front: "Cita 4 tipos de trabajos que quedan EXCLUIDOS del Régimen General por no considerarse relación laboral.", back: "Trabajos amistosos, benévolos, de buena vecindad, y los prestados a título de emérito (ej. profesores eméritos)." },
    { id: 29, front: "¿Qué porcentaje EXACTO de participación en el capital social determina 'control efectivo en todo caso' (no admite prueba en contrario) según el A305?", back: "Al menos el 50% del capital social." },
    { id: 30, front: "¿Qué porcentaje EXACTO de participación individual genera la PRESUNCIÓN (admite prueba en contrario) de control efectivo, sin necesitar ningún otro requisito?", back: "Al menos 1/3 (33,33%) del capital social." },
    { id: 31, front: "¿Qué combinación EXACTA de porcentaje + requisito genera la presunción de control efectivo por la vía de 'dirección y gerencia'?", back: "Poseer al menos 1/4 (25%) del capital social Y ejercer funciones de dirección y gerencia." },
    { id: 32, front: "Para la presunción de control efectivo POR SUMA FAMILIAR (cónyuge/parientes hasta 2º grado), ¿qué porcentaje conjunto se exige y qué requisito adicional es imprescindible?", back: "Que la suma con familiares hasta 2º grado alcance al menos el 50%, Y que exista CONVIVENCIA entre ellos. Sin convivencia no se pueden sumar los porcentajes aunque el parentesco sea de 2º grado." },

    // --- Bloque 5: Encuadramientos específicos ---
    { id: 33, front: "¿Qué porcentaje mínimo de ingresos de un único cliente convierte a un autónomo en TRADE?", back: "Al menos el 75% de sus ingresos por rendimientos de trabajo y actividades económicas provenientes de un único cliente (Trabajador Autónomo Económicamente Dependiente)." },
    { id: 34, front: "¿En qué régimen queda el NOTARIO o REGISTRADOR, y en cuál su PERSONAL de notaría/registro?", back: "El notario o registrador → RETA (cuenta propia). El personal que trabaja para ellos (empleados de la notaría) → Régimen General, cuenta ajena." },
    { id: 35, front: "¿En qué régimen se encuadran los trabajadores de VENTA AMBULANTE por cuenta propia?", back: "RETA." },
    { id: 36, front: "¿En qué régimen se encuadran los ARTISTAS que trabajan por cuenta propia?", back: "RETA." },
    { id: 37, front: "¿Qué actividad concreta excluye a un trabajador del RETA para pasar al régimen especial correspondiente?", back: "La actividad marítimo-pesquera — esos trabajadores van a REMAR (Régimen Especial de Trabajadores del Mar), no al RETA." },
    { id: 38, front: "Según el artículo 306, ¿qué tipo de socio queda EXCLUIDO por completo del sistema de Seguridad Social (ni siquiera se da de alta)?", back: "El socio de una sociedad de capital, sea o no administrador, cuando la sociedad no realiza actividad empresarial/profesional sino que se limita a la mera administración del patrimonio de los socios (sociedad patrimonial pura, el socio no trabaja)." },
    { id: 39, front: "¿Cómo se llama el sistema especial para EMPLEADOS DE HOGAR?", back: "SEH — Sistema Especial de Empleados de Hogar (dentro del Régimen General)." },
    { id: 40, front: "¿Cómo se llama el sistema especial para trabajadores AGRARIOS POR CUENTA AJENA?", back: "SEA — Sistema Especial Agrario (dentro del Régimen General)." },
    { id: 41, front: "¿Cómo se llama el sistema especial para trabajadores AGRARIOS POR CUENTA PROPIA?", back: "SETA — Sistema Especial de Trabajadores por Cuenta Propia Agrarios (dentro del RETA)." },

    // --- Bloque 6: Casos prácticos resueltos en clase ---
    { id: 42, front: "CASO: Sara tiene una ferretería en Salamanca y contrata a su hijo Lucas, de 27 años, CON QUIEN NO CONVIVE. ¿Régimen y exclusión exactos?", back: "Régimen General, cuenta ajena, SIN exclusión de desempleo (inclusión plena, cotiza por todo). Al faltar la convivencia no se cumplen los 4 requisitos del A12, así que se trata como una contratación cualquiera." },
    { id: 43, front: "CASO: Daniela tiene una tienda de reparación de móviles. Su hija Encarnación, 42 años, discapacidad auditiva del 65%, CONVIVE con ella y trabaja en el negocio. ¿Régimen y exclusión exactos?", back: "Régimen General, cuenta ajena, EXCLUIDA la cobertura por desempleo — sin exigir que sea su primera alta (porque el 65% ya está en el tramo superior). La edad de 42 años es irrelevante." },
    { id: 44, front: "CASO (Computadores SL, reparto inicial 33,33% cada uno): Manuel y Rubén son hermanos que conviven y son administradores con DG; José solo trabaja sin cargo. ¿Encuadramiento de Manuel?", back: "RETA, en situación de presunción — cumple varias vías: 33,33% individual (≥1/3), y además 33,33%+33,33% de Rubén conviviente = 66,66% (≥50%)." },
    { id: 45, front: "Mismo caso anterior: ¿encuadramiento de José, que solo tiene 33,33% y ningún cargo ni DG?", back: "RETA, en situación de presunción — le basta con el 33,33% individual (≥1/3) aunque no tenga ni funciones de dirección y gerencia ni cargo de administrador." },
    { id: 46, front: "CASO: José (33,33% en Computadores SL) deja de trabajar en la sociedad, aunque mantiene su participación. ¿Qué le ocurre a su encuadramiento?", back: "Queda EXCLUIDO por completo del sistema (art. 306): al no trabajar, es un mero socio capitalista que cobra dividendos — no necesita alta en ningún régimen." },
    { id: 47, front: "CASO: nuevo reparto en Computadores SL — Manuel 40%, José 40%, Rubén 20% (Manuel y Rubén siguen conviviendo, con DG). ¿Encuadramiento de Rubén?", back: "RETA, en situación de presunción — su 20% individual no le basta, pero sumado al 40% de su hermano conviviente Manuel alcanza el 60% (≥50%)." },
    { id: 48, front: "CASO: en el reparto anterior (Manuel 40%, Rubén 20%, José 40%), Manuel y Rubén DEJAN de convivir. ¿Qué cambia en el encuadramiento de Rubén?", back: "Pasa de RETA a Régimen General, ASIMILADO a cuenta ajena con exclusión de desempleo y Fogasa. Al perder la convivencia ya no puede sumar el 40% de Manuel, y su 20% individual no alcanza ningún umbral de control — pero sí tiene DG y es administrador (caso ámbar)." },
    { id: 49, front: "CASO: nuevo reparto en Computadores SL — Manuel 20%, Rubén 25%, José 55% (Manuel y Rubén vuelven a convivir). ¿Encuadramiento de José?", back: "RETA, con CONTROL EN TODO CASO (no admite prueba en contrario) — su 55% individual supera por sí solo el umbral del 50%." },
    { id: 50, front: "Mismo reparto anterior (Manuel 20%, Rubén 25%, José 55%): ¿por qué Rubén va al RETA pero Manuel NO?", back: "Rubén (25% + funciones de dirección y gerencia) cumple exactamente el umbral de 'al menos 1/4 + DG' → RETA en presunción. Manuel (20%) no llega a ningún umbral individual, y la suma con Rubén (20%+25%=45%) tampoco alcanza el 50% → Régimen General, asimilado a cuenta ajena." },

    // --- Bloque 7: Tarjetas recicladas de tests reales (Destino Funcionario) ---
    { id: 51, front: "Según el A137 LGSS, ¿cuáles son los 3 motivos por los que un trabajo NO está comprendido en el Régimen General?", back: "1) Servicios amistosos, benévolos o de buena vecindad (ejecutados ocasionalmente). 2) Los que den lugar a inclusión en algún régimen especial. 3) Profesores universitarios eméritos y personal licenciado sanitario emérito. TRAMPA: si el servicio benéfico-social es RETRIBUIDO, sí implica afiliación y alta — no confundir 'benéfico-social' con 'benévolo'." },
    { id: 52, front: "¿En qué régimen se encuadran los miembros del Cuerpo de Registradores de la Propiedad, Mercantiles y de Bienes Muebles, y los del Cuerpo de Aspirantes?", back: "En el RETA (Régimen Especial de Trabajadores por Cuenta Propia o Autónomos) — igual que los notarios. En cambio, el PERSONAL contratado por ellos (empleados del registro/notaría) sí va al Régimen General." },
    { id: 53, front: "Según el A305 LGSS, ¿cuáles son los 3 requisitos EXACTOS (edad, ajenidad, actividad) para estar obligatoriamente incluido en el RETA?", back: "1) Ser persona física MAYOR DE 18 AÑOS (no 16, aunque en España se pueda trabajar desde los 16 — el RETA exige 18). 2) Actividad fuera del ámbito de dirección y organización de otra persona (por CUENTA PROPIA). 3) Dar o no ocupación a trabajadores por CUENTA AJENA (no cuenta propia — esa es otra trampa típica del examen)." },
    { id: 54, front: "CASO 'Cuatro B' (4 hermanas socias a partes iguales... bueno, reparto real: Berta 25%, Bárbara 25%, Brígida 30%, Brenda 20%; Berta y Bárbara conviven; Brígida y Bárbara ejercen DG; solo Bárbara es administradora). ¿Encuadramiento de Bárbara?", back: "RETA, en situación de PRESUNCIÓN (salvo prueba en contrario). Aunque ella sí ejerce DG y es administradora, esos datos son irrelevantes aquí porque YA tiene el control por la vía de la convivencia (25%+25% con Berta = 50%) — las funciones de DG/administradora solo importan cuando NO hay control." },
    { id: 55, front: "Mismo caso 'Cuatro B': ¿encuadramiento de Berta (25%, convive con Bárbara, SIN funciones de DG ni cargo)?", back: "RETA, en situación de PRESUNCIÓN — igual que Bárbara, porque juntas (Berta+Bárbara conviviendo) alcanzan el 50% del capital. El hecho de que Berta no tenga DG ni cargo no importa: ya tiene el control por la suma con su hermana conviviente." },
    { id: 56, front: "Mismo caso 'Cuatro B': si Brígida (30% + DG, sin cargo de administradora, sin convivir con nadie de la empresa) vendiera la MITAD de sus acciones a una hermana, quedándose con 15%, ¿cómo queda encuadrada?", back: "Cuenta ajena en el Régimen General, SIN ninguna exclusión ni asimilación. Con 15% no tiene control, y aunque ejerce DG, al NO ser administradora/consejera no se cumplen las 3 condiciones del caso 'ámbar' — falla una y ya es 'rojo' (cuenta ajena pura)." },
    { id: 57, front: "Mismo caso 'Cuatro B': Brenda (20% del capital, NO trabaja en la empresa familiar, trabaja como asalariada en OTRA empresa) — ¿qué tipo de trabajadora es respecto a la empresa familiar?", back: "Ante la ausencia de vinculación expresa a una empresa concreta en la pregunta, lo correcto es tratarla como trabajadora por cuenta ajena del Régimen General (por el trabajo que sí realiza, en la otra empresa). Respecto a la empresa familiar en la que no trabaja, no generaría alta alguna por ese negocio." },
    { id: 58, front: "Mismo caso 'Cuatro B': si Bárbara y Berta DEJARAN de convivir (mismo 25% cada una), ¿cambia su encuadramiento?", back: "Berta pierde la presunción de control (con solo 25% individual no cumple ningún umbral) → pasa a cuenta ajena del Régimen General (no tiene DG). Bárbara SÍ mantiene la presunción, porque ella ejerce funciones de DG y su situación ya no depende de la convivencia con Berta — ojo, aquí hay truco: no es que mantenga el control por otra vía de %, sino que se sigue analizando su propia situación (repasa bien el caso 3 y 4 del A305 con tu instructor si tienes dudas de detalle)." },
    { id: 59, front: "CASO 'Zanahoria Naranja': Mónica, 26 años, hija de los dueños autónomos, convive con ellos y trabaja en la frutería mientras estudia. ¿Cuál es su encuadramiento POSIBLE (no único)?", back: "PODRÍA ser cuenta ajena del Régimen General con exclusión de desempleo (art. 12.2, hija menor de 30 que convive) — pero es solo una posibilidad, ya que sus padres también podrían optar por darla de alta como autónoma en el RETA, en cuyo caso SÍ tendría cobertura de desempleo." },
    { id: 60, front: "CASO 'Zanahoria Naranja': Genaro Romero, discapacidad del 65%, contratado por un Centro Especial de Empleo (CEE) dedicado a distribución de alimentos. ¿Encuadramiento según el A13?", back: "Trabajador por cuenta ajena, en el régimen de la Seguridad Social que corresponda a la actividad del CEE (no necesariamente Régimen General)." },
    { id: 61, front: "CASO 'Zanahoria Naranja': David, hermano de uno de los dueños autónomos, vive con su propia esposa (NO convive con su hermano), es contratado en la frutería. ¿Encuadramiento?", back: "Cuenta ajena del Régimen General, SIN exclusión alguna. Aunque hay parentesco (hasta 2º grado) y ocupación en el centro de trabajo, faltan los otros 2 requisitos del A12.1 (convivencia y estar a su cargo) — con que falte solo uno de los 4 requisitos, ya no aplica la presunción de cuenta propia." },
    { id: 62, front: "CASO 'Zanahoria Naranja': Fernando, 32 años, hijo de los dueños, discapacidad física del 45%, YA HABÍA TRABAJADO ANTES (no es su primera alta en el sistema), convive con sus padres. ¿Encuadramiento?", back: "RETA (cuenta propia), NO Régimen General. TRAMPA: aunque tiene entre 33%-65% de discapacidad (tramo que normalmente permite cuenta ajena con exclusión de desempleo), ese tramo EXIGE que sea su primera alta en el sistema — y Fernando ya había trabajado antes, así que no cumple ese requisito adicional y se le aplica la regla general del A12 (cuenta propia salvo prueba en contrario, que aquí sí se cumple: vínculo, convivencia, ocupación y a su cargo)." },
    { id: 63, front: "CASO 'Zanahoria Naranja': Antonio Riesco, discapacidad del 33%, contratado por el mismo CEE (FRIGOINSA). ¿Es suficiente el 33% para quedar incluido según el A13?", back: "Sí. El A13 exige que la PLANTILLA del CEE tenga al menos 70% de trabajadores con discapacidad ≥33% — el requisito individual para CADA trabajador es solo ≥33%, no 65%. Con el 33% de Antonio, es más que suficiente." }
];